### ISSUE TITLE
请问LoginService是怎么实现的啊？

### ISSUE THREAD

**Issue by qujihan** [longer96/CDTU#4]

**Comment by 18214091046** [comment]
哎，你是指哪一个项目，邮件上不知道呢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月26日(周六) 凌晨3:28
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [longer96/CDTU] 请问LoginService是怎么实现的啊？ (#4)




 
Closed #4.
